<a href="https://colab.research.google.com/github/18520918/CS114.L11.KHCL/blob/master/LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Thuật toán Logistic Regression.**<br>
**2. Cách thực hiện bài toán.**<br>
**3. Đánh giá mô hình.**

In [ ]:
import pandas as pd
import numpy as np
from google.colab import files 
import io
from sklearn.linear_model import LogisticRegression
from google.colab import files
uploaded = files.upload()
data = pd.read_csv(io.BytesIO(uploaded['fetal_health.csv']))

Saving fetal_health.csv to fetal_health.csv


In [ ]:
for i in data.columns:
  print(i, data[i].isnull().sum())

baseline value 0
accelerations 0
fetal_movement 0
uterine_contractions 0
light_decelerations 0
severe_decelerations 0
prolongued_decelerations 0
abnormal_short_term_variability 0
mean_value_of_short_term_variability 0
percentage_of_time_with_abnormal_long_term_variability 0
mean_value_of_long_term_variability 0
histogram_width 0
histogram_min 0
histogram_max 0
histogram_number_of_peaks 0
histogram_number_of_zeroes 0
histogram_mode 0
histogram_mean 0
histogram_median 0
histogram_variance 0
histogram_tendency 0
fetal_health 0


In [ ]:
X = data.iloc[:,:-1]
Y = data.iloc[:,-1]

In [ ]:
Y

0       2.0
1       1.0
2       1.0
3       1.0
4       1.0
       ... 
2121    2.0
2122    2.0
2123    2.0
2124    2.0
2125    1.0
Name: fetal_health, Length: 2126, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
X_train, X_test, y_train, y_test = train_test_split(X,Y,train_size=0.5, random_state=0)

logis = LogisticRegression().fit(X_train,y_train)
y_pred = logis.predict(X_test)
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
acc = accuracy_score(y_test,y_pred)
print(acc)
print(classification_report(y_test,y_pred))

[[793  23  13]
 [ 76  66   7]
 [  5  13  67]]
0.8711194731890874
              precision    recall  f1-score   support

         1.0       0.91      0.96      0.93       829
         2.0       0.65      0.44      0.53       149
         3.0       0.77      0.79      0.78        85

    accuracy                           0.87      1063
   macro avg       0.77      0.73      0.75      1063
weighted avg       0.86      0.87      0.86      1063



/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
